server.port=${LINK_SERVICE_PORT:8081}
app.base-url=${LINK_SERVICE_BASE_URL:http://localhost:8080}

# Datasource Configuration
spring.datasource.url=${LINK_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/linkpulse}
spring.datasource.username=${POSTGRES_USER:linkpulse_user}
spring.datasource.password=${POSTGRES_PASSWORD:linkpulse_secret_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true