server.port=${LINK_SERVICE_PORT}
app.base-url=${LINK_SERVICE_BASE_URL}

# Datasource Configuration
spring.datasource.url=${LINK_SERVICE_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true